"""Prompt packs for coding-agent UI generation."""

from __future__ import annotations

from everyharness.agents.detect import AgentId
from everyharness.plugin.protocols import ModelRef

_BASE_INSTRUCTIONS = """
You are helping build a small web/GUI wrapper around a local ML model managed by everyharness.

Goals:
1. Read `model-card.json` for model metadata and harness hints.
2. Produce a minimal, runnable UI that calls the model via harness CLI or serve.
3. Keep dependencies light; prefer a single-page app or simple FastAPI + static files.
4. Document how to run the UI in README.md inside this directory.
5. Do not exfiltrate data; assume offline/local execution.

The everyharness CLI for this model:
  everyharness run {model_id} -- <harness args>
  everyharness serve {model_id}   # if the harness supports OpenAI-compatible serving

Model reference URI: {model_uri}
Detected kind: {model_kind}
""".strip()


_AGENT_WRAPPERS: dict[AgentId, str] = {
    "cursor": "Use Cursor's agent mode. Open this folder as the workspace root.",
    "claude": "Run `claude` in this directory and paste AGENT_PROMPT.md if needed.",
    "copilot": (
        "In VS Code / Cursor, open Copilot Chat with this folder "
        "and reference AGENT_PROMPT.md."
    ),
    "pi": "Launch the Pi agent CLI pointed at this directory.",
    "codex": "Run the Codex CLI with this directory as context.",
}


def build_agent_prompt(model: ModelRef, agent: AgentId) -> str:
    """Build the main agent prompt for UI scaffolding."""
    kind = model.kind or "unknown"
    body = _BASE_INSTRUCTIONS.format(
        model_id=model.id,
        model_uri=model.uri,
        model_kind=kind,
    )
    wrapper = _AGENT_WRAPPERS.get(agent, "")
    return f"{body}\n\n## Agent notes ({agent})\n{wrapper}\n"


def build_readme(model: ModelRef, agent: AgentId, dest_name: str) -> str:
    """README for the harness-ui output directory."""
    return f"""# harness-ui — {model.id}

Generated by `everyharness ui {model.id} --agent {agent}`.

## Contents

- `model-card.json` — model metadata from the everyharness registry
- `AGENT_PROMPT.md` — paste into your coding agent to scaffold a UI
- `manifest.json` — generation metadata

## Quick start

1. Open this directory in your editor or agent workspace.
2. Read `AGENT_PROMPT.md` and ask your agent to build a minimal UI.
3. Run predictions via everyharness:

```bash
everyharness run {model.id} --help
```

## Agent

Selected agent: **{agent}**

If the CLI is missing, run `everyharness ui {model.id} --agent {agent}` again for install hints.

Output path: `{dest_name}`
"""
